langchain-ai/langsmith-sdk

js/src/cli/main.ts
python/langsmith/cli/main.py

We've been seeing some issues with updating containers using the previous setup. Explicitly pull then run

Pull and run separately

---

js/src/client.ts
python/langsmith/client.py

Currently presumes localhost if not specified.
Suggested change would be to assume prod `https://api.smith.langchain.com` if an api key is specified, otherwise fall back to localhost.
Would eliminate 1 strictly required env var

Update default url

---

python/langsmith/__init__.py
python/langsmith/run_helpers.py
python/tests/unit_tests/test_run_helpers.py

- Update the inputs so that `**kwargs` specified values are included at the top level
- If function returns a dict, apply that directly

Update decorator map

---

js/src/schemas.ts

This is useful to trace full inputs in runnable .transform() calls.

Update RunUpdate schema to allow updated inputs

---

python/langsmith/client.py

The `allowed_methods` keyword argument was added to `urllib3.util.Retry` in version 1.26.
This PR alters `langsmith.client._default_retry_config` to:
1. Check the version of `urllib3`
2. If version is >= 1.26, use the `allowed_methods` keyword of the `Retry` object
3. Otherwise, do not use the `allowed_methods` keyword.

Support urllib3<1.26

---

js/src/client.ts
python/langsmith/client.py
python/tests/integration_tests/test_client.py

Context: feedback is entering the write queue and so we can't get the info back in the response.
- Update the return object to be populated from the creation object rather than the API response.
- Permit manual specification of the ID's
- Update the evaluate_run() return object to be the evaluationresult

Write Queue Compatible

---

js/src/client.ts
js/src/schemas.ts
python/langsmith/client.py
python/langsmith/schemas.py

Same needs to be done in JS SDK

Sort by dotted order in py sdk

---

python/langsmith/client.py

Some people want to override our request session. We should enable them to do this when creating their client by creating their own session and passing it in. TODO to port to javascript.

Add session param to SDK client.

---

python/langsmith/run_helpers.py
python/pyproject.toml

The outer context should be re-assigned to whatever it was before and not overwritted to whatever was manually passed in

Change which parent run tree is re-assigned

---

js/src/client.ts
js/src/tests/client.int.test.ts
python/langsmith/client.py
python/langsmith/schemas.py

Validate uuids

---

python/langsmith/client.py
python/langsmith/utils.py
python/poetry.lock
python/pyproject.toml
python/tests/unit_tests/test_utils.py

We plan to introduce an environment variable in hosted langserve that will overwrite the project used for traces from hosted deployments. We don't centralize how we refer to projects in any of our repos, so in order to ensure that our tracing works properly and our project selection is consistent, we need to introduce a shared method for getting the project that we can use throughout our different repos

Add method to consistently get project

---

python/langsmith/client.py
python/langsmith/evaluation/evaluator.py
python/langsmith/schemas.py
python/tests/unit_tests/test_client.py

Add methods from the Annotation Queue API to the python package.
Also improve the run evaluator decorator and add a URL for example objects

Add Annotation Queue API Methods

---

js/package.json
js/src/client.ts

Reverts a change [here](https://github.com/langchain-ai/langsmith-sdk/pull/346) that causes an infinite loop.
(see the line `bodyParams.cursor = cursors.next;`)

fix infinite loop when paginating via cursor

---

js/src/client.ts

The current logic to fetch the langsmith host url unintentionally turns the default langsmith url of `https://api.smith.langchain.com` into an invalid url of `https:/.smith.langchain.com` because it matches on the /api portion.
This PR changes the logic to exempt those cases where the subdomain begins with `api` so that the correct host url is returned.

fix url hosting url parse

---

.github/workflows/js_test.yml
.github/workflows/release_js.yml
js/package.json
js/scripts/bump-version.js
js/scripts/check-version.js
js/src/client.ts
js/src/index.ts
js/src/utils/env.ts
python/langsmith/client.py
python/langsmith/env/_runtime_env.py
python/pyproject.toml
python/tests/unit_tests/test_client.py

Main changes are to start tracking JS SDK version in runtime information AND to include that info in the user-agent header so we can more easily provide guidance when there are error logs

Bump: Add User-Agent information

---

python/langsmith/cli/docker-compose.yaml

- add healthchecks on upstream containers
- wait until clickhouse migration has finished before starting backend and queue

Fix docker compose

---

python/langsmith/client.py
python/tests/integration_tests/test_runs.py

- controlled by LANGCHAIN_TRACING_SAMPLING_RATE
- if a POST was allowed then the matching PATCH is allowed too
- applied on both single and batch tracing endpoints

Add optional tracing sampling rate to langsmith sdk

---

python/langsmith/client.py
python/tests/unit_tests/test_client.py

Better default handling for:
1. Regular python objects
2. dataclasses
3. attrs

Better Serialize

---

python/langsmith/run_helpers.py
python/tests/unit_tests/test_run_helpers.py

Change to let you do this:
```
from langsmith import traceable
@traceable
def foo():
return "bar"
```
Rather than ONLY this:
```
from langsmith import traceable
@traceable() # <- need to call the function
def foo():
return "bar"
```

Enable no args decorator

---

python/langsmith/client.py
python/tests/unit_tests/test_client.py

Fall back to repr when you reach a certain depth of regular class traversal

Update default python serialization

---

js/src/client.ts
js/src/tests/batch_client.test.ts

@hinthornw @nfcampos I think this is better than doing a check on startup?

Adds batch tracing support check for JS

---

python/langsmith/client.py
python/langsmith/run_trees.py
python/langsmith/schemas.py
python/tests/integration_tests/test_client.py

as seen in the [official docs](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow) datetime.datetime.utcnow() is being deprecated and the suggested function to use instead is datetime.datetime.now(datetime.UTC) (which also supports the .isoformat() function)

fix depracation warning of .utcnow()

---

js/src/client.ts
js/src/run_trees.ts
js/src/tests/run_trees.test.ts

We were initializing a client by default every time, which means if you don't have an env var set, you can't use the run tree.
Should we remove the thrown error altogether on client initialization? Why was that added in the first place?
@hinthornw @dqbd

Allow manually specified client in run tree with no env vars

---

python/langsmith/client.py
python/tests/unit_tests/test_client.py

This lets you scope hide inputs/outputs to a client. It also lets you add custom filters (rather than just masking everything.
You could then use this in the traceable decorator or langchain tracer to filter runs within a given trace.
It would _not_ facilitate filtering on a span level though, since it only sees the inputs/outputs and the client is shared within a trace.
Alternatives could include a single function (filter_run) that takes in a Run object, though then we'd have to re-construct the run within the client, which is a bit annoying

Custom hide/filter inputs/outputs

---

README.md
js/README.md
python/README.md
python/pyproject.toml

Support for custom hide_inputs/outputs in python

[Python] 0.1.15

---

python/pyproject.toml

Fix a bug that occurs when using Datadog (they patch threading.lock, making it non-deep-copyable)

[Python] 0.1.16

---

python/langsmith/client.py
python/pyproject.toml
python/tests/unit_tests/test_client.py

- Call info within tracing queue
- Default to batching even if info endpoint fails
If you turn batching off, you have to make your own tracer / traceable flow that handles threading yourself now.

fix threading

---

python/langsmith/client.py
python/langsmith/schemas.py
python/tests/unit_tests/test_client.py

* Allow user to set `LANGSMITH_ENDPOINT` and `LANGSMITH_API_KEY` (in addition to `LANGCHAIN_ENDPOINT` and `LANGCHAIN_API_KEY`). This priority will be former > latter > passed-in parameter.
* Allow user to set `LANGSMITH_RUNS_ENDPOINTS` environment variable or pass in `api_urls` which are a map of api urls to api keys. The first element will be used for all requests, whereas all elements will be used for writing (Runs only)

feat: allow multiple write URLS for runs in SDK (python)

---

js/src/tests/client.int.test.ts
python/langsmith/beta/_evals.py

Usage:
```
from langsmith.beta import compute_test_metrics
def my_evaluator(run, example):
score = "foo" in run.outputs['output']
return {"key": "is_foo", "score": score}
compute_test_metrics("fun-mirror-32", [my_evaluator])
```

Compute test metrics

---

python/langsmith/evaluation/__init__.py
python/langsmith/evaluation/evaluator.py

Also auto-trace in the runevaluator if possible
Related to: https://github.com/langchain-ai/langsmith-sdk/pull/542

Update exports of eval types

---

python/langsmith/__init__.py
python/langsmith/_testing.py
python/langsmith/client.py
python/langsmith/run_helpers.py
python/langsmith/run_trees.py
python/langsmith/wrappers/_openai.py

Basically, each unit test <-> example, and a single test run creates or updates a dataset and generates runs + metrics
Improvements to be made:
Later:
- Printout the test suite results
- Print out the examples updated/created/deleted/unused
- caching
- etc.

Add a testing decorator

---

.github/actions/python-integration-tests/action.yml
.github/workflows/python_test.yml
js/package.json
js/src/index.ts
python/langsmith/_internal/_aiter.py
python/langsmith/_testing.py
python/langsmith/client.py
python/langsmith/run_helpers.py
python/pyproject.toml
python/tests/integration_tests/test_client.py
python/tests/unit_tests/test_client.py
python/tests/unit_tests/test_run_helpers.py
python/tests/unit_tests/test_testing.py

(slightly breaking for comparison flows for unit testing)
1.  Update the ID representation to mostly match the pytest format of `path/to/test_file.py::test_function[arg#-arg#-arg#]` instead of 
2. Fallback to `repr` of object fo rexample inputs/outputs
Why?
- In unit testing, the example inputs/outputs are less important. Want to permit non-serializable objects.
- Don't want to keep creating populating new examples with new IDs just because the non-serializable object includes its memory ID in its repr

Fix Example Serialization

---

python/langsmith/_testing.py
python/langsmith/client.py
python/langsmith/run_helpers.py
python/pyproject.toml
python/tests/evaluation/test_evaluation.py
python/tests/external/test_instructor_evals.py

1. This should be marked as a `pass: None` to not factor into aggregate score
2. The run shouldn't be marked as an error
The changes in this PR reflect these desiderata

Add support for handling pytest.skip in @unit

---

js/package.json
js/src/index.ts
js/src/tests/traceable.test.ts
js/src/tests/utils/tree.ts
js/src/traceable.ts

fix(traceable): async iterators lose context

---

js/src/run_trees.ts
js/src/tests/traceable.test.ts
js/src/traceable.ts

- **Send inputs even when patching run**
- **Collect deferred values during invocation via proxy**
- **Handle ReadableStream in input**

feat(js): trace deferred values in input

---

js/src/run_trees.ts
js/src/tests/traceable.test.ts
js/src/tests/wrapped_openai.int.test.ts
js/src/wrappers/openai.ts

- **Make sure we're only allowing wrapping once**
- **Allow passing name to runnable config like**

fix(js): throw when wrapping same client twice, allow passing name in argsConfigExtra

---

python/langsmith/_internal/_embedding_distance.py

[Py] Ignore optional numpy import

---

js/src/singletons/traceable.ts

As `langsmith/singletons/traceable` is an entrypoint from langchain as well, we need to reexport the type

chore(js): reexport TraceableFunction type from singleton

---

js/.gitignore
js/package.json
js/scripts/create-entrypoints.js
js/src/evaluation/langchain.ts
js/src/langchain.ts
js/src/run_trees.ts
js/src/tests/lcls_handoff.int.test.ts
js/src/utils/warn.ts
js/tsconfig.json
js/yarn.lock

Moves the inline code snippet from langsmith new experiment pane to library instead. New entrypoint to make sure users don't need to depend on full-blown `langchain` when they can only depend on `@langchain/core`

feat(js): move `getLangchainCallbacks` to TypeScript SDK

---

python/langsmith/_expect.py
python/langsmith/wrappers/_openai.py
python/pyproject.toml
python/tests/unit_tests/test_expect.py

Previously, you couldn't write `expect(None).to_*`

[Python] Add Null Sentry

---

python/langsmith/evaluation/_arunner.py
python/langsmith/evaluation/_runner.py
python/langsmith/evaluation/evaluator.py
python/langsmith/run_helpers.py
python/tests/unit_tests/test_run_helpers.py

Improves for python >= 3.10. Should in theory not change anything for users of 3.8 and 3.9 (at least, things pass in our 3.8 linting here... Apologies in advance to any mypy acolytes on 3.{8,9} who gain undesired linting errors after this change)
Uses:
1. ParamSpec (available in 3.10 and onwards)
2. Protocols (already used)
Even though python doesn't naturally support keyword-only concatenation, we can work around this with protocols and duck typing to communicate the actual returned type of "the same function signature + a keyword only langsmith_extra arg"
Python's typing situation makes it hard to make everyone happy, but hopefully this strikes a better compromise than before (typing kwargs as Any in the wrapped function; too lenient)
Closes #551

[Python] Improve @traceable typing

---

python/langsmith/run_trees.py
python/tests/integration_tests/wrappers/test_openai.py

Since creating a client also creates a new thread, there's a non-negligible creation time for this if you're starting many traces at once.
Caching, of course, removes this overhead.

[Python] Cache default run tree client

---

python/langsmith/client.py
python/langsmith/run_trees.py
python/langsmith/utils.py
python/langsmith/wrappers/_openai.py
python/tests/unit_tests/test_client.py

For some code paths currently, if you mutate inputs/outputs within Xs of invocation, langsmith will log the mutated value, which is confusing and the wrong behavior.
We can't naively use deepcopy, as many valid python objects cannot be copied.
This PR creates a compromise solution that attempts to deepcopy and then falls back to copying up to depth 4 while handling errors.
Will hopefully resolve #706 . Placed before the `hide_*` as well so that if people want to mutate the dict when filtering it doesn't impact the execution flow.

[Python] Deeper Copy

---

python/langsmith/run_trees.py
python/pyproject.toml
python/tests/unit_tests/test_run_trees.py

1. from_runnable_config doesn't lbyl to see if the parent is in the order_map. Should fix
2. events are null by default here but are populated in langchain, meaning run trees cant be treated as interchangeable in the base tracer.

[Python] Handoff Bugs

---

python/langsmith/run_trees.py
python/pyproject.toml
python/tests/unit_tests/test_run_trees.py

Also needed for the handoff. I had neglected to see that some batch ingestion operations depend on it.
Closes https://github.com/langchain-ai/langsmith-sdk/issues/751
Closes https://github.com/langchain-ai/langchain/issues/22353
Closes https://github.com/langchain-ai/langsmith-sdk/issues/752

[Python] Infer parent_run_id in from_dotted_order

---

python/langsmith/utils.py
python/pyproject.toml

Catch all exceptions. This was failing when deepcopy raised an error like SparkRuntime.. or the like

safer exception

---

python/langsmith/run_helpers.py

If the `selected_wrapper` function contains a `**kwargs` parameters, `sig.replace(...)` breaks because of the following error:
```
ValueError: wrong parameter order: variadic keyword parameter before keyword-only parameter
```
This PR fixes the above error.

fix sig.replace to account for kwargs

---

python/langsmith/_testing.py
python/pyproject.toml
python/tests/evaluation/test_evaluation.py

For unit testing.
Also fix issue where test suite name isn't being honored

[Python] Set example creation time to experiment start time

---

python/langsmith/__init__.py
python/langsmith/_expect.py
python/langsmith/_testing.py
python/tests/evaluation/test_evaluation.py
python/tests/external/test_instructor_evals.py

Most times, people use this decorator for integration-like testing. Better to keep it generic  as `@test`
We'll keep `@unit` around for backwards compat

[Python] s/unit/test/g

---

python/langsmith/run_helpers.py
python/langsmith/utils.py
python/pyproject.toml
python/tests/unit_tests/test_client.py
python/tests/unit_tests/test_utils.py

for "tracing is enabled". 
This isn't relevant for `@traceable` only tracing, but comes into play if you're crossing over to langchain.
Also fix a bg in `trace` context manager where it would be persisting the run tree inferred by headers beyond its desired lifespan

[Python] Check if mid-trace

---

js/.gitignore
js/package.json
js/scripts/create-entrypoints.js
js/src/anonymizer/index.ts
js/src/client.ts
js/src/index.ts
js/src/tests/anonymizer.test.ts
js/src/tests/utils/mock_client.ts
js/tsconfig.json
js/yarn.lock
python/langsmith/__init__.py
python/langsmith/anonymizer.py
python/langsmith/client.py
python/pyproject.toml
python/tests/unit_tests/test_anonymizer.py

Expected TypeScript usage:
```ts
import { createAnonymizer } from "langsmith/anonymizer"
// provide list of regex and replacement values
const anonymizer = createAnonymizer([
{ pattern: "...", replace: "[value]" }
])
const client = new Client({ anonymizer })
// replace string values
const anonymizer = createAnonymizer((value) => value.replace("...", "[value]"))
```
Expected Python usage:
```python
from langsmith.anonymizer import create_anonymizer
anonymizer = create_anonymizer([{"pattern": r"...", "replace": "[value]"}])
client = Client(anonymizer=anonymizer)
anonymizer = create_anonymizer(lambda text: r"...".sub("[value]", text))
```

feat(python, js): add anonymizer API

---

js/.eslintrc.cjs
js/package.json
js/src/anonymizer/index.ts
js/src/index.ts
js/src/utils/lodash/LICENSE
js/src/utils/lodash/assignValue.ts
js/src/utils/lodash/baseAssignValue.ts
js/src/utils/lodash/baseSet.ts
js/src/utils/lodash/castPath.ts
js/src/utils/lodash/eq.ts
js/src/utils/lodash/getTag.ts
js/src/utils/lodash/isIndex.ts
js/src/utils/lodash/isKey.ts
js/src/utils/lodash/isObject.ts
js/src/utils/lodash/isSymbol.ts
js/src/utils/lodash/memoizeCapped.ts
js/src/utils/lodash/set.ts
js/src/utils/lodash/stringToPath.ts
js/src/utils/lodash/toKey.ts
js/yarn.lock

The `lodash.set` package is unmaintained and has a CVE: https://security.snyk.io/package/npm/lodash.set
The current `lodash` version has no CVEs: https://security.snyk.io/package/npm/lodash
I've inlined the relevant set functionality from the current version of `lodash`.
Let's be more careful with adding deps in the future!
@dqbd @nfcampos @agola11

js[patch]: Inline lodash.set functionality to patch vulnerability

---

python/langsmith/run_helpers.py
python/tests/unit_tests/test_run_helpers.py

currently there is no way to dynamically override the `name` argument that could be passed into `traceable`. This allows the run name to be overridden by `langsmith_extra`

support overridding name in langsmith_extra

---

python/Makefile
python/langsmith/client.py
python/langsmith/run_helpers.py
python/langsmith/run_trees.py
python/poetry.lock
python/pyproject.toml
python/tests/integration_tests/test_client.py
python/tests/integration_tests/test_runs.py
python/tests/unit_tests/test_run_helpers.py

Previously, the trace() context manager would trace no matter what. Now, respect the context var that's set if you use tracing_context()
Additionally, respect the enabled arg in @traceable even if project_name is manually defined.

[Python] Respect enabled in context manager

---

python/langsmith/run_helpers.py
python/pyproject.toml
python/tests/integration_tests/test_runs.py
python/tests/unit_tests/test_run_helpers.py

- currently happens in two situations
- for errored runs, when fetching the langsmith run url for a debug print statement (which most people won't  even want in production, but thats a separate issue)
- for all runs, when batch tracing is turned off

py: Fix traceable decorator blocking asyncio event loop

---

js/src/singletons/types.ts
js/src/tests/traceable.test.ts
js/src/traceable.ts

iterables can have other properties

fix(js): keep traceable wrappedFunc returnValue props

---

python/langsmith/_internal/_aiter.py
python/langsmith/run_helpers.py
python/pyproject.toml
python/tests/unit_tests/test_run_helpers.py

We were previously setting the context vars in a separate context and then letting it be gc'd.
Fixes https://github.com/langchain-ai/langsmith-sdk/issues/892

[Python] Fix nesting in async trace context manager

---

python/langsmith/run_helpers.py
python/langsmith/utils.py
python/pyproject.toml
python/tests/unit_tests/test_run_helpers.py

It's hard to use in production if it has a different switch than the rest of the tracing code.

Respect env var in langsmith.trace

---

js/src/client.ts
js/src/tests/client.int.test.ts

When pushing an updated manifest to an existing prompt and not specifying any other options, updatePrompt threw an error that we need to be updating something, but we're updating the manifest. This fixes.

fix: push existing prompt without specifying any other options

---

js/src/tests/client.int.test.ts
python/langsmith/client.py
python/tests/unit_tests/test_client.py

Previously required {"results": [EvaluationResult]}
Now can be: {"results": [EvaluationResultLike]}

Accept EvaluationResults with dict

---

python/langsmith/client.py
python/langsmith/run_trees.py
python/tests/integration_tests/test_client.py

This change makes it possible to update the name of a run after it has been created. Previously, run names could not be modified once set.

feat: support `name` parameter to `update_run`

---

python/langsmith/client.py
python/langsmith/run_trees.py
python/tests/integration_tests/test_client.py

This change makes it possible to update the name of a run after it has been created. Previously, run names could not be modified once set.

feat: support `name` parameter to `update_run` (#927)

---

js/package.json
js/yarn.lock

This PR addresses `uuid.validate` rejecting UUIDv6. Alternatively we can inline the regex used

fix(js): upgrade to uuid@10 for UUIDv6 support

---

python/langsmith/async_client.py
python/langsmith/client.py
python/langsmith/utils.py
python/pyproject.toml
python/tests/unit_tests/test_client.py

For a long time we have been raising an error if you create a client that connects to the public endpoint without specifying an api key.
This makes it possible for someone with inadequate testing to push code into prod leaving the LANGSMITH_TRACING=true on but without setting an api key.
This would raise a lot of error logs in the best case and crash a deployment in the worst case.
Would prefer to just warn and not have tracing rather than impact the actual runtime.

[Py] Warn if api key not provided

---

python/langsmith/evaluation/_runner.py
python/tests/unit_tests/evaluation/test_runner.py

Seeing large slowdowns when using `evaluate()` compared to naive `ThreadPoolExecutor`. The specific slowdown happens on a cpu-bound call to BeautifulSoup, which balloons from 0.1s -> 5 seconds (and sometimes up to 60+ seconds based on concurrency).
First, I noticed that the majority of the time in bs4 init was actually empty space, which made me think that: (1) there was GIL contention, or (2) there was some lock being placed on the thread.
I took a look at the `ExperimentResults` implementation, and noted that in the infinite while loop, there was an `is_active` call inside of the thread lock, and since `is_active` has nontrivial overhead, and this loop was running even if there were no results, we were incurring this overhead over and over.
To confirm, I noticed that in the main thread …

Optimize CPU-bound Task Execution by Replacing Thread Lock with Producer-Consumer Pattern

---

python/langsmith/evaluation/evaluator.py
python/langsmith/run_helpers.py

The top-level trace to an evaluator contains the full run and example. The run object can be nested and quite large. It's also harder to catch with he default hide_inputs since it's a nested object.
Default to using the repr and setting a threshold.
These spans aren't typically high-value anyway

[Python] Default process_inputs for evaluators

---

python/langsmith/run_trees.py

Precursor for another PR I have.
This makes it interoperable with the `Run` object in core and doesn't incur overhead of initializing a langsmith client if you aren't logging to langsmith (but are using a tracer in langchain for another purpose)

[Py] Lazy client initialization in run tree

---

python/langsmith/client.py

Adding method for removing a run from an annotation queue (#1027)

---

python/langsmith/cli/docker-compose.yaml

this adds environment variables to support the new self-hosted SSO auth mode: https://docs.smith.langchain.com/self_hosting/configuration/sso#oauth20-and-oidc-without-pkce

chore: update docker-compose for new OAuth mode

---

python/langsmith/client.py
python/poetry.lock
python/pyproject.toml
python/tests/integration_tests/test_client.py
python/tests/unit_tests/test_client.py

- Use streaming multipart encoder form requests_toolbelt
- Currently dump each part to json before sending the request as that's the only way to enforce the payload size limit
- When we lift payload size limit we should implement true streaming encoding, where each part is only encoded immediately before being sent over the connection, and use transfer-encoding: chunked

Implement "streaming" multipart requests to multipart endpoint

---

python/langsmith/client.py

- This is harder to get to work correctly in api, and not useful given we mostly don't send these anymore

py: Stop sending serialized as a separate part

---

python/langsmith/client.py
python/langsmith/utils.py

- 408 is "client took too long to send request body"

py: Retry on 408

---

js/package.json
js/src/index.ts
js/src/tests/traceable.test.ts
js/src/tests/wrapped_openai.int.test.ts
js/src/wrappers/openai.ts
js/yarn.lock

This fixes tracing of `openai.beta.chat.completions.parse`. There were issues caused by OpenAI methods internally calling others.

fix(js): More deeply copy OpenAI SDK when wrapping

---

js/src/tests/run_trees.int.test.ts

There were some issues with creating and deleting a project of the same name in an integration test - I added a uuid in project name and we still cleanup by deleting the now unique project name.

Add UUID to project name in integration test

---

python/langsmith/client.py

- Also up the max nr of tracing threads, and lower the scale up threshold

py: Enable multipart endpoint without feature flag

---

python/langsmith/client.py
python/pyproject.toml

- requests doesn't seek the encoder object to the start when starting a new retry, so we need to create a new encoder instead

fix: Create new multipart encoder for each retry attempt

---

js/package.json
js/src/client.ts
js/src/index.ts
js/src/utils/fast-safe-stringify/index.ts

Further investigation into #1101

fix(js): Further reduce blocking behavior, try naive stringification instead of circular detection

---

python/langsmith/_internal/_background_thread.py
python/langsmith/client.py
python/langsmith/schemas.py
python/pyproject.toml
python/tests/integration_tests/test_client.py
python/tests/unit_tests/test_client.py

When multipart is enabled, use same tracing_queue and multipart endpoint to send feedback as well.

feat(py): Add multipart feedback ingestion

---

python/langsmith/_internal/_serde.py
python/tests/unit_tests/test_client.py

Avoid running into the error for "missing self" when serializing
Fixes #1116

Skip model_dump for classes

---

python/langsmith/_internal/_serde.py
python/tests/unit_tests/test_client.py

Apply `_simple_default` serialization on dict keys to resolve this exception
```python
Traceback (most recent call last):
File "/Users/brendan/.local/share/virtualenvs/core-bRkH1-KB/lib/python3.11/site-packages/langsmith/client.py", line 281, in _dumps_json_single
return orjson.dumps(
^^^^^^^^^^^^^
TypeError: Dict key must a type serializable with OPT_NON_STR_KEYS
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/Users/brendan/.local/share/virtualenvs/core-bRkH1-KB/lib/python3.11/site-packages/langsmith/client.py", line 5802, in _tracing_thread_handle_batch
client.multipart_ingest_runs(create=create, update=update, pre_sampled=True)
File "/Users/brendan/.local/share/virtualenvs/core-bRkH1-KB/lib/python3.11/site-packages/langsmith/ …
```

Fix serialization of `pydantic.BaseModel` fields with `pathlib.Path` dict keys

---

js/src/client.ts
js/src/tests/traceable.int.test.ts

Standardize with the Python SDK, the delay for batch flushing in multipart JS should also be 250ms

Remove initial timeout, the batch timeout is now always 250ms

---

js/package.json
js/src/client.ts
js/src/index.ts
js/src/tests/batch_client.test.ts

fix(js): Use batch endpoint instead of individual run endpoint in case of server info fetch failure

---

python/langsmith/client.py
python/tests/unit_tests/test_run_helpers.py

Make is_public optional to avoid hiding public prompts unintentonally

[Python] push_prompt update

---

python/langsmith/evaluation/_runner.py
python/langsmith/evaluation/evaluator.py
python/tests/unit_tests/evaluation/test_evaluator.py
python/tests/unit_tests/evaluation/test_runner.py

```python
from langsmith import evaluate
def foo(run, example):
return 0
def bar(run, example):
return "long"
def app(inputs):
return inputs
evaluate(app, data="Sample Dataset 3", evaluators=[foo, bar, baz])
```

python[patch]: evaluators can return primitives

---

python/langsmith/schemas.py

A huge percentage of our `aevaluate` calls were trying to serialize part of the example to send in the evaluator trace (where we used to show the first 10k characters). Let's just not do that. 
```
async def run_abenchmark(
n_examples=200, 
min_size=1000000, 
max_size=4000000, 
n_evaluators=5,
min_llm_time=0.2,
max_llm_time=1.2,
n_concurrency=None
):
inputs = [
{"key": "a" * randint(min_size / 2, max_size / 2)}
for _ in range(n_examples)
]
outputs = [
{"key": "b" * randint(min_size / 2, max_size / 2)}
for _ in range(n_examples)
]
if ls_client.has_dataset(dataset_name="jake_benchmarking"):
ls_client.delete_dataset(dataset_name="jake_benchmarking")
print("Creating dataset...")
dataset = ls_client.create_dataset("jake_benchmarking")
print("Uploading examples...")
for i in range(0, …
```

perf: cut down cpu time of aevaluate by 30% on 1-4MB examples with this one trick

---

python/langsmith/__init__.py

Each call is like 1-3ms, and we call to get the version as part of every client request's headers. If you're running an eval over a lot of traces (say 10 evaluators on 1k examples), that's slow. Esp if just doing custom code evaluators which should run fast. 
(ran on 2k smallish examples w 10 evaluators)

nit: stop calling importlib on every api req

---

js/src/tests/evaluate_comparative.int.test.ts
js/src/tests/vercel.int.test.ts

saw some flakiness in comparative evals stuff too, but not skipping those because seems less common
if we do want to remove comparative evals: https://github.com/langchain-ai/langsmith-sdk/pull/1232/commits/c07164a846d9cd131e7bb737c68e40dfe103c27b

skip flaky js integration test

---

.github/workflows/build_langsmith_pyo3_wheels.yml

GitHub doesn't allow running new workflows from branches if the workflow by that name doesn't already exist on the main branch. I'm creating this placeholder workflow to work around that, so I can then trigger and test the workflow from my own branch.

Add placeholder workflow for building PyO3 wheels.

---

python/langsmith/anonymizer.py
python/tests/unit_tests/test_anonymizer.py

when the processor is initialized, I recompile the pattern if necessary

recompile pattern if needed before its used to mask sensitive info

---

.github/workflows/build_langsmith_pyo3_wheels.yml

Building on Windows seems to fail with a linking error, the same one as here: https://github.com/PyO3/maturin-action/issues/292

Build 3.13 wheels for all platforms except Windows.

---

vendor/pyo3/pyo3-ffi/src/lib.rs
vendor/pyo3/src/lib.rs

We vendor `pyo3` and its related libraries, but we depend on users' build tools to build wheels when a suitable wheel is not found on PyPI. The source distribution only includes the actual source code of `pyo3` et al, but their source code indirectly depends on non-source artifacts, such as files in their `guide/` or `examples/` directories. Those directories are not part of the source distribution, so locally building the wheel fails.
This PR removes those links, since they are only used for doc comments and aren't relevant to the actual operation of our library.

Remove links in vendored code that point outside the sdist source code.

---

.github/workflows/build_langsmith_pyo3_wheels.yml

Otherwise, PRs that touch *only* the workflow file aren't tested on the workflow, and might break it.

Ensure the wheel-building workflow runs if it's changed.

---

.github/workflows/build_langsmith_pyo3_wheels.yml

Due to the above, we should just build on the newer macOS. Those wheels *should* work on any reasonably-new macOS version, or else Python would have made the wheels different across versions like they are for `musllinux` vs regular linux.

Python wheels don't distinguish between macOS versions.

---

js/package.json
js/src/client.ts
js/src/index.ts

Allows for interoperability in LangChain when initializing tracer with clients if different LangSmith versions are resolved:
```ts
import { Client } from "langsmith";
// `@langchain/core` may have a different internal version of `langsmith`
import { LangChainTracer } from "@langchain/core/tracers";
const client = new Client();
const tracer = new LangChainTracer({
client, // Will type error if resolutions are bad
});
```

feat(js): Expose light interface for tracing client

---

python/langsmith/client.py
python/langsmith/evaluation/_runner.py
python/tests/unit_tests/test_client.py

take: we should aim for users to not have to import/instantiate anything other than Client

python[patch]: client.evaluate, client.aevaluate

---

js/src/evaluation/evaluate_comparative.ts

integration tests currently broken

js[patch]: fix evaluateComparative

---

rust/Cargo.lock
rust/Cargo.toml
rust/crates/langsmith-pyo3/Cargo.toml
rust/crates/langsmith-pyo3/src/py_run.rs
rust/crates/langsmith-tracing-client/Cargo.toml
rust/crates/langsmith-tracing-client/benches/json_serialization_benchmark.rs
rust/crates/langsmith-tracing-client/benches/tracing_client_benchmark.rs
rust/crates/langsmith-tracing-client/src/client/async_enabled/processor.rs
rust/crates/langsmith-tracing-client/src/client/blocking/processor.rs
rust/crates/langsmith-tracing-client/src/client/run.rs
rust/crates/langsmith-tracing-client/tests/test_run.rs
rust/crates/langsmith-tracing-client/tests/tracing_client_test.rs

`sonic_rs` has a serious perf regression in a recent release, and doesn't seem particularly reliable as a library. Our perf-sensitive code is now running `orjson`, so the bits still using `sonic_rs` aren't very hot anymore. Let's switch to `serde_json` for easier maintainability.

Remove `sonic_rs` and switch to `serde_json`.

---

.github/workflows/build_langsmith_pyo3_wheels.yml
rust/crates/langsmith-pyo3/pyproject.toml

Drop support for Python 3.8 from the PyO3 bindings, and don't build Python 3.8 wheels when publishing.

langsmith no longer supports Python 3.8, so neither should our PyO3 code

---

rust/Cargo.lock
rust/crates/langsmith-tracing-client/Cargo.toml
rust/crates/langsmith-tracing-client/tests/tracing_client_test.rs

The multipart library we were originally using as a dev-dependency was many years out of date, and relied on many outdated and vulnerable dependencies. Switching to a newer library for the same workload avoids those old dependencies and the security alerts associated with them.

Drop outdated/vulnerable dependencies by using a newer multipart library

---

.github/workflows/rust_test.yml
rust/crates/langsmith-pyo3/src/py_run.rs
rust/crates/langsmith-tracing-client/benches/json_serialization_benchmark.rs

Run tools like `clippy`, `cargo fmt`, `cargo doc`, and tests over our Rust code in CI.

Run tests and lint for Rust code in CI.

---

.github/workflows/test_langsmith_nodejs.yml

Workflows have to exist on `main` in order to be runnable on other branches. I'd like to merge this now so I can properly test the full workflow on a branch.

Add placeholder workflow for testing `langsmith_nodejs` Rust code.

---

rust/Cargo.lock
rust/Cargo.toml

We don't want to bloat our wheels with two different major versions of the same library.

Upgrade `thiserror` from v1 to v2.

---

python/langsmith/client.py
rust/crates/langsmith-pyo3/src/blocking_tracing_client.rs
rust/crates/langsmith-pyo3/src/py_run.rs

Implement the `update_run()` client method in the Rust PyO3 bindings, and call it from the Python client if the Rust bindings are enabled.

Add Rust implementation for Python client's `update_run()` method.

---

.github/workflows/build_langsmith_pyo3_wheels.yml

Explain how to fix the case where the publishing tag and the Cargo.toml / wheels version don't match.

Improve the error message for tag and version mismatch error case.

---

rust/crates/langsmith-tracing-client/src/client/blocking/processor.rs

When serializing Python objects to JSON, `orjson` includes a trailing null byte since it's producing a C-string which is null-terminated.
However, when sending HTTP multipart data, we send the JSON with an explicit content length value, so the trailing null byte is neither needed nor expected. So strip the trailing null (if present) before sending `inputs` and `outputs`.

Ensure pre-formatted JSON data doesn't contain trailing null bytes.

---

rust/crates/langsmith-tracing-client/src/client/blocking/processor.rs
rust/crates/langsmith-tracing-client/src/client/run.rs

If sending a `Create` together with an `Update` for the same ID, merge them into the same operation instead of sending two separate operations in the same batch.

Merge `Update` operations into `Create` operations in the same batch.

---

python/bench/tracing_client_via_pyo3.py
python/bench/tracing_rust_client_bench.py
rust/crates/langsmith-pyo3/src/blocking_tracing_client.rs
rust/crates/langsmith-tracing-client/src/client/blocking/processor.rs
rust/crates/langsmith-tracing-client/src/client/blocking/tracing_client.rs
rust/crates/langsmith-tracing-client/src/client/run.rs

If the Python application wants to exit (or the client just gets garbage collected), we want to finish sending any batched requests before proceeding with the GC or app shutdown.
Normally, Python will make sure to shut down any Python-side threads before allowing the program to exit. But it's completely unaware of Rust's own threads, so it can't shut them down or wait for them. This is why we need to explicitly make sure they complete their work and shut down on their own. The `Drop` trait in Rust runs when the value is dropped, and we ensure we shut down the background threads *only* when we're certain the only `Arc` copy of the Rust client is the one we're holding (and which is about to go out of scope).

Drain the Rust client when its last copy in Python is dropped.

---

python/langsmith/beta/_evals.py

This error occurs because the dataset examples were created AFTER the runs (which we copy to the experiment), thus the experiment cannot determine which examples to associate the experiment with which leads to the experiment view not loading.

fix time for runs in convert_runs_test

---

js/package.json
js/src/client.ts
js/src/index.ts
js/src/tests/batch_client.test.ts

Should help deal with poor batching for high-volumes of long-running traces in serverless environments
CC @barberscott @nhuang-lc

feat(js): Adds manual flush mode

---

python/langsmith/client.py

Set compressed condition as `elif` to avoid ingestion on both rust and compressed paths

fix: Separate rust and compressed ingestion paths

---

python/langsmith/_internal/_background_thread.py

Correctly determine the size of compressed runs buffer before checking if we should flush it.
Periodically flush zstd buffer and get the correct size.

fix: Flush zstd and correctly get buffer size

---

python/langsmith/client.py

Need to rewind the buffer back to the start for the next endpoint, so we send the entire data stream

fix: Reset buffer after sending to server

---

python/langsmith/_internal/_background_thread.py

Compression improves run throughput and memory usage, but performance is still slower than expected for power users due to excessive threads and small payloads. SDK users can improve the throughput for larger payloads and higher trace counts by making the run count batch ingest config globally configurable.
* Created an environment variable `LANGSMITH_BATCH_INGEST_SIZE_LIMIT` to configure run count.
* This takes precedence over the `/info` api response and any value passed directly to the client batch ingest config.
Setting a higher run count increased compressed runs throughput by **~80-100%** depending on run count and payload size.

feat: Make size_limit (max run count per batch) globally configurable via env var

---

js/src/client.ts

This PR introduces functionality to use the LangSmith JS SDK to retrieve the total number of runs in an annotation queue.
I came across the following endpoints in the LangSmith API documentation (Redoc link) but am unsure which one is appropriate for this purpose:
/api/v1/annotation-queues/{queue_id}/total_size
/api/v1/annotation-queues/{queue_id}/size

feat(js): Add method to get size of annotation queue

---

python/langsmith/_internal/_serde.py
python/tests/integration_tests/test_client.py

Without this code, Pydantic models containing surrogates get serialized differently than models that don't contain surrogates. This leads to a less smooth user experience in LangSmith for users whose data contains surrogates.
With this fix, Pydantic models and other tricky Python data types are always serialized in the same way, regardless of whether they contain surrogates or not.

Make `pydantic` model serialization consistent regardless of surrogates.

---

python/langsmith/client.py
python/langsmith/evaluation/_runner.py
python/langsmith/schemas.py
python/tests/integration_tests/test_client.py

need to land https://github.com/langchain-ai/langchainplus/pull/7415 first

add mime type to attachment info

---

python/langsmith/_internal/_serde.py
rust/crates/langsmith-pyo3/src/py_run.rs
rust/crates/langsmith-pyo3/src/serialization/mod.rs

From the Rust bindings, import the `_serialize_json` function from `langsmith._internal._serde`, then use it as the default fallback if `orjson` serialization can't handle some object. This makes the Rust serialization code equivalent to the `_orjson.dumps()` call inside `langsmith._internal._serde.dumps_json`.
I will handle UTF surrogate characters in a subsequent PR.

Serialize pydantic and other tricky objects correctly from Rust.

---

rust/Cargo.lock
rust/Cargo.toml
rust/crates/langsmith-tracing-client/Cargo.toml
rust/crates/langsmith-tracing-client/src/client/errors.rs
rust/crates/langsmith-tracing-client/src/client/mod.rs
rust/crates/langsmith-tracing-client/src/client/streaming/mod.rs
rust/crates/langsmith-tracing-client/src/client/streaming/multipart_writer.rs
rust/crates/langsmith-tracing-client/src/client/streaming/processor.rs
rust/crates/langsmith-tracing-client/src/client/streaming/tracing_client.rs

Uses a hand-written streaming multipart writer that can wrap a zstd compressor, so that we try to not keep `QueuedRun` values in memory any longer than strictly necessary.
A "TODO" for tomorrow's revamp of the error types is to switch from unbounded to bounded channels and either use the `QueueFull` error variant or just block until the channel frees up. @agola11 do you have a preference one way or the other? This governs what happens in the rare instance if e.g. the server is much too slow at ingesting data and traces are piling up on the client. We can either drop data, or force the client to slow down, and this is a product-level decision.
It's a good idea to use bounded channels over unbounded ones, even if the bound is huge and shouldn't ever be hit. Bounded channels are both more …

Implement streaming multipart zstd compression.

---

rust/crates/langsmith-pyo3/src/blocking_tracing_client.rs
rust/crates/langsmith-tracing-client/src/client/streaming/tracing_client.rs

Builds upon #1413 and uses that functionality in the PyO3 crate.
This is a major breaking change in the API, so make it be part of a v0.2.0-rc1 release.

Switch PyO3 to streaming zstd-compressed multipart Rust client.

---

python/langsmith/_internal/_background_thread.py
python/langsmith/_internal/_compressed_traces.py
python/langsmith/_internal/_operations.py
python/langsmith/client.py
python/tests/unit_tests/test_client.py

Compress feedback along with runs using the same compression buffer and background thread
* Renamed compressed runs variables to compressed traces
* Compress feedback along with runs
* Added additional client ref to `num_refs` to account for compression bg thread.
Tested locally to ensure feedback ingest works with and without compression
Added unit tests for feedback ingest with compression

Compress create feedback

---

js/package.json
js/src/index.ts
js/src/jest/reporter.ts
js/src/tests/jestlike/vitest_separate_file.vitesteval.ts
js/src/utils/jestlike/reporter.ts
js/src/vitest/reporter.ts

Please merge after #1476 since this has a version bump

fix(js): Fix multiple datasets in same test file for Vitest, improve reporter output

---

python/langsmith/run_helpers.py

Fixes an issue where the traceable decorator injects a "config" keyword argument into the target function's kwargs, causing an error when the function does not expect it.
Solution is to pop "config" from `kwargs` before invoking `_setup_run`. 
Applied change across all relevant wrappers (async, async generator, sync, generator, stream, and async stream wrappers) 
Resolves: https://github.com/langchain-ai/langsmith-sdk/issues/1551 and https://github.com/langchain-ai/langsmith-sdk/issues/1436

Fix 'unexpected keyword argument "config"' error in traceable decorator

---

python/langsmith/run_trees.py
python/pyproject.toml
python/tests/integration_tests/fake_server.py
python/tests/unit_tests/test_run_helpers.py
python/tests/unit_tests/test_utils.py

It creates a cyclic reference which slows down garbage collection and makes it easy to introduce memory leaks

Unset parent_run in run_tree

---

python/langsmith/client.py

We should use the global otel tracing provider if it's set outside of LangSmith

Fix setting otel tracing provider

---

python/langsmith/wrappers/_openai_agents.py

questions i haven't really thought through yet:
- do we really only want to bubble up responses spans? could a tool be the last span (if theres a handoff?)
- should we bubble up response/tool spans to agent spans as well, not just the root trace?
- could this accidentally lead to large memory usage?

add inputs/outputs to root trace

---

python/langsmith/run_helpers.py

these aren't real serializations and they cause downstream issues in langsmith

fix(py): drop traceable serialized data

---

python/langsmith/_internal/otel/_otel_exporter.py
python/pyproject.toml

This change fixes an issue in the LangSmith OTEL integration where metadata attributes with a value of None were being set on spans, causing errors like:
Invalid type NoneType for attribute 'langsmith.metadata.ls_temperature' value.
Changes:
Added a check to ensure that metadata values are only set if they are not None.
Bumped the package version from 0.3.24 to 0.3.25.
Resolves: https://github.com/langchain-ai/langsmith-sdk/issues/1640

patch[python]: Don't set metadata values if the value is None

---

python/langsmith/_internal/_background_thread.py
python/langsmith/_internal/_compressed_traces.py
python/langsmith/_internal/_operations.py
python/langsmith/client.py
python/pyproject.toml

Enabling this logging is useful for pinpointing where traces are being lost. Right now it's difficult to tell if they are making it from the sdk into LangSmith or not

patch[python]: Add debug logging for batch requests to LangSmith

---

python/langsmith/client.py

The LangSmith SDK currently defaults to the LangSmith endpoint, if an API key isn't provided and we're tracing via OTEL, don't throw a Warning about a missing API key
Resolves: https://github.com/langchain-ai/langsmith-sdk/issues/1646

patch(python): Don't throw warning for missing API key in otel mode

---

python/langsmith/_internal/_background_thread.py
python/pyproject.toml

If we fail to drain the compression buffer, we shouldn't shut down the background thread. We should also add logging if draining the buffer fails.

patch[python]: Don't shut down compression thread if drain fails

---

js/package.json
js/src/index.ts
js/src/run_trees.ts
js/src/schemas.ts
python/langsmith/run_trees.py
python/pyproject.toml

Currently, patch requests don't carry information about the project they are associated with. This causes upstream issues on ingestion when the patch is sent separately and we don't know the trace tier of the project, and thus, assign it the default tracing project tier. The result of this is that we upgrade the s3 urls post ingestion API: resulting in higher storage costs and an increase in class A operations.

patch[python, js]: Update runs with project name

---

python/docs/requirements.txt

… (#1663)"
This reverts commit d45c267306443344e8659569618f1630a7e025e7.

Revert "docs[fix]: `-e` install `langsmith` so api refs are available (no longer using rtd)

---

.github/workflows/python_test.yml
python/Makefile
python/langsmith/__init__.py
python/pyproject.toml

To speed up import times.
Add check in CI to avoid misalignment.
(drops raw import langsmith times from .05 to .02 for me)

Make __version__ a constant

---

js/package.json
js/src/client.ts
js/src/index.ts
js/src/tests/batch_client.test.ts
js/src/tests/traceable_langchain.test.ts

`traceable`'s typing makes this more difficult to update `processInputs` and `processOutputs` in a similar way - would say let's just add here to unblock async PII masking use cases.

feat(js): Allow async functions in client hideInputs and hideOutputs

---

python/langsmith/__init__.py
python/langsmith/wrappers/_agent_utils.py
python/langsmith/wrappers/_openai_agents.py
python/pyproject.toml

Currently our openai agents sdk calls create/update run methods without `trace_id` and `dotted_order`, which means tracing will happen in the main thread.
This fix sets those variables in the agents integration
Issue discovered in: https://github.com/openai/openai-agents-python/issues/529

chore[python]: Set dotted order for openai agents sdk integration

---

js/package.json
js/src/index.ts
js/src/tests/jestlike/jest.test.ts
js/src/tests/jestlike/vitest.vitesteval.ts
js/src/utils/jestlike/globals.ts
js/src/utils/jestlike/index.ts

feat(js): Allow .concurrent, throw error when nesting describe blocks in Jestlike runners

---

python/langsmith/client.py
python/langsmith/utils.py
python/tests/integration_tests/test_async_client.py

prevent one run creation failure from block all run creations, in case of multiple write endpoints

fix(py): try/except writing to multiple endpoints

---

python/langsmith/__init__.py
python/langsmith/evaluation/_arunner.py
python/langsmith/evaluation/_runner.py
python/pyproject.toml
python/tests/unit_tests/evaluation/test_runner.py

Add support for accessing example metadata in target
```python
def target(inputs: dict, metadata: dict) -> dict: ...
```

feat(py): support metadata in target func

---

python/langsmith/__init__.py
python/langsmith/_internal/_background_thread.py
python/langsmith/_internal/otel/_otel_exporter.py
python/langsmith/client.py
python/pyproject.toml

Adds support for context propagation. This means LangSmith spans can be nested within larger OTel traces, maintaining parent-child relationships between spans.
Can now nest LangSmith operations within an existing OTel context:
```
with tracer.start_as_current_span("langchain_invoke"):
chain.invoke(...)
```
Resolves: https://github.com/langchain-ai/langsmith-sdk/issues/1682

feat[python]: OTel context propagation

---

python/langsmith/__init__.py
python/langsmith/_internal/_background_thread.py
python/langsmith/client.py
python/pyproject.toml

The batch compression tracing thread was occasionally shutting itself down mid-session, which then also shut down the main tracing queue.
The control thread decided a Client was “orphaned” by comparing sys.getrefcount() against active_count of the ThreadPoolExecutor. The compression loop would exit early, leaving traces unsent.
Don't include ThreadPoolExecutor threads in the refcount calculation, since they won't block process shutdown are the executor is defined globally, so won't be affected by creating multiple clients
Additionally sets futures to be a WeakSet, so that completed futures that are GC'd automatically get discarded from the set, preventing memory leaks
Resolves: https://github.com/langchain-ai/langsmith-sdk/issues/1630

fix[python]: Correct client reference counting in compression thread 

---

python/langsmith/__init__.py
python/langsmith/run_helpers.py
python/langsmith/run_trees.py
python/pyproject.toml

Useful in conjunction with https://github.com/langchain-ai/langchain/pull/31090.
Then from within a langchain runnable, you can do.
```
def my_node(state):
if rt := ls.get_current_run_tree():
rt.set(inputs={"foo": state.foo}, outputs={"bar": "my_bar"})
```
And have it override the defaults. Useful for filtering PII or large values etc.

Add RunTree.set() support

---

js/src/client.ts

Add GroupRunsParams interface and implement groupRuns method for run grouping
Function implemented for [Group Runs](https://api.smith.langchain.com/redoc#tag/run/operation/group_runs_api_v1_runs_group_post)

feat(js) Add function to get Group Runs

---

js/src/traceable.ts

`inputs` and `outptus` get wiped out later on in the run tree, so the types should just omit them.

fix(js): Narrow overly broad traceable type

---

js/src/client.ts
js/src/tests/client.int.test.ts
python/langsmith/client.py
python/langsmith/run_helpers.py
python/tests/integration_tests/test_client.py

* Make `child_run_ids` not a default field in select.
* Also fix the `load_child_runs` path to use query by trace.

Remove default for fetching child_run_ids from the SDK

---

python/langsmith/__init__.py
python/langsmith/client.py
python/pyproject.toml

Specifying run_id and trace_id is confusing and often redundant, given feedback is usually provided for root runs

feat(py): create_feedback with trace_id only

---

python/langsmith/client.py
python/tests/unit_tests/test_client.py

The `_convert_stored_attachments_to_attachments_dict` function was attempting to download attachments using `requests.get(value["presigned_url"])`, but `value["presigned_url"]` often contains only an API path (e.g., `/api/public/download?jwt=...`) rather than a complete URL. This caused `requests.get()` to fail with connection errors when trying to download attachment data.
- **Modified function signature**: Updated `_convert_stored_attachments_to_attachments_dict` to accept an optional `api_url` parameter
- **Added URL construction logic**: When `api_url` is provided, the function now uses the existing `_construct_url` helper to properly construct the complete URL by combining the API base URL with the attachment path
- **Backward compatibility**: Made `api_url` optional (defaults to …

fix(py): Fix URL construction in attachment downloading

---

python/langsmith/_internal/_compressed_traces.py

Seeing near identical compression ratio for level 1 vs 3. This will also reduce cpu usage from the SDK

Reduce zstd compression level to 1

---

js/src/singletons/traceable.ts
js/src/singletons/types.ts
js/src/tests/traceable_langchain.test.ts
js/src/traceable.ts

fix(js): Use context placeholder to preserve LangChain context variables even if tracing is disabled

---

js/package.json
js/src/index.ts
js/src/tests/vercel/vercel_node_otel.int.test.ts
js/src/tests/vercel/vercel_rate_limit.int.test.ts
js/src/vercel.ts

- Mark top level AI SDK runs as chain runs instead of LLM to avoid double token counting issues (already in new method)
- Properly pass through model call errors and treat usage as 0

fix(js): Fix AI SDK token counting issues for legacy exporter

---

js/package.json
js/src/client.ts
js/src/index.ts

In the case that a stream request cannot successfully be sent to LangSmith multipart tracing, fallback to tracing via buffered body.  This is a less performant method of tracing, but adding a fallback makes requests more resilient.

If stream fails, fallback to buffered body request

---

js/package.json
js/src/experimental/otel/exporter.ts
js/src/index.ts
js/src/traceable.ts

Rely on span attribute rather than sending it in the header
Very frustrating that headers are not configurable at runtime in the exporter superclass :(

fix(js): Respect project names set at runtime for OTEL exported traces

---

js/package.json
js/src/index.ts
js/src/run_trees.ts

This is difficult to test in langsmith due to circular deps but verified independently and will add a test to LangChain.

fix(js): Fallback to parent run id if parent run is not present in run trees loaded from LangChain

---

js/package.json
js/src/client.ts
js/src/index.ts
js/src/tests/client.test.ts
python/langsmith/__init__.py
python/langsmith/client.py
python/pyproject.toml
python/tests/unit_tests/test_client.py

We were not correctly filtering patch runs when the post would get filtered, meaning large amounts of patch requests were being sent to ingest API and counting toward usage limits, but not actually getting ingested.
Check patch trace id against trace id list, only remove trace ids from list for root runs.
Use consistent hashing based on run_id to sample both post and patch run ids equally, prevents storage of uuids (minimal memory overhead)
Added unit tests confirming filtering logic correctly applies to both post and patch

patch(python, js): Fix sampling logic for patch runs

---

python/langsmith/client.py
python/langsmith/run_helpers.py
python/langsmith/run_trees.py
python/langsmith/utils.py
python/tests/unit_tests/test_client.py
python/tests/unit_tests/test_replica_endpoints.py

Backport the replica endpoints functionality from JavaScript to Python, enabling runs to be sent to multiple LangSmith instances with different API keys and URLs via replicas, instead of a separate slot.
1. New replica format: Added WriteReplica type supporting api_url, api_key,  project_name, and updates
2. Environment variable support: LANGSMITH_RUNS_ENDPOINTS now parsed into replicas (replaces old _write_api_urls logic)
3. Tracing context: Baggage headers now support both legacy and new replica formats for distributed tracing
4. Client methods: create_run() and update_run() accept optional api_key/api_url parameters
5. Backward compatibility: Legacy tuple format (project_name, updates) still supported
1. LANGSMITH_RUNS_ENDPOINTS no longer populates _write_api_urls (now handled via …

feat(python): Add replica endpoints support to Python SDK

---

python/langsmith/run_helpers.py
python/langsmith/run_trees.py
python/tests/unit_tests/test_replica_endpoints.py
python/tests/unit_tests/test_run_helpers.py
python/tests/unit_tests/test_run_trees.py

Adds support for distributed tracing where parent projects receive the full trace while child projects receive a sliced trace starting from the distributed parent ID.
Requires manual configuration: The `reroot: True` flag must be explicitly set in replica configuration for each child project that should receive sliced traces.
1. Cross workspace support
2. Tracing will only work for a parent-child relationship. It will not work for chains of 3 or more distributed graphs (e.g., A→B→C). Only the immediate parent-child pair will have proper trace slicing.

feat(python): Add distributed tracing with sliced traces for child projects

---

python/tests/unit_tests/test_client.py
python/tests/unit_tests/test_replica_endpoints.py

Theory: pytest doesn't clear functools.lru_cache on test teardown

fix(py): Remove monkeypatching and ensure env var cache is cleared

---

js/package.json
js/src/index.ts
js/src/run_trees.ts
js/src/tests/replica_endpoints.test.ts
python/langsmith/__init__.py
python/langsmith/run_trees.py
python/pyproject.toml
python/tests/unit_tests/test_replica_endpoints.py

Support tracing to multiple orgs/workspaces via LANGSMITH_RUNS_ENDPOINTS by supporting dict format for LANGSMITH_RUNS_ENDPOINTS
```
{
"api_url": "x",
"api_key": "y",
}
```

feat(python, js): Support tracing to multiple orgs/workspaces

---

.github/workflows/link-check.yml
.mlc_config.json

This link was frequently 429'ing: https://github.com/langchain-ai/helm/blob/main/charts/langsmith/docker-compose/docker-compose.yaml
See: https://github.com/gaurav-nelson/github-action-markdown-link-check?tab=readme-ov-file#too-many-requests

fix(ci): Allow 429s for markdown link checks in CI

---

python/langsmith/__init__.py
python/langsmith/_internal/otel/_otel_exporter.py
python/pyproject.toml

Remove custom dotted order attribute from python OTEL integration. Originally used for batch processing optimizations, but caused issues with framework interoperability. Performance concerns can be remedied with langsmith otel proxy

chore(python): Remove langsmith dotted order attribute from otel integration

---

python/langsmith/__init__.py
python/langsmith/run_trees.py
python/pyproject.toml
python/tests/unit_tests/test_replica_endpoints.py

This PR fixes the logic for converting legacy replicas in `run_trees`. We were incorrectly expecting lists when legacy replica items were actually tuples

fix(python): legacy replicas conversion

---

python/langsmith/run_helpers.py

This already works as expected, and returning str is suggested by https://docs.smith.langchain.com/observability/how_to_guides/trace_generator_functions
Closes #1949
Otherwise mypy complains:
```py
@traceable("llm", reduce_fn=lambda chunks: "".join(chunks))
def stream_llm(self, prompt: str) -> Iterator[str]:
...
```
```
src/prediction/llm_client.py:810: error: No overload variant of "traceable" matches argument types "str", "Callable[[Any], str]"  [call-overload]
src/prediction/llm_client.py:810: note: Possible overload variants:
src/prediction/llm_client.py:810: note:     def [P`-1, R] traceable(func: Callable[P, R]) -> SupportsLangsmithExtra[P, R]
src/prediction/llm_client.py:810: note:     def traceable(run_type: Literal['tool', 'chain', 'llm', 'retriever', 'embedding', 'prompt', …
```

fix(py): adjust traceable reduce_fn type to allow returning str

---

python/langsmith/__init__.py
python/langsmith/_internal/otel/_otel_client.py
python/langsmith/_internal/otel/_otel_exporter.py
python/langsmith/client.py
python/langsmith/utils.py
python/pyproject.toml
python/tests/unit_tests/test_multiple_endpoints.py
python/uv.lock

**Issue:** for dynamic values like env var, you usually want to check them inside the instance or function, not at import time. because under the hood, python Imports are cached (in sys.modules), so in the case of some customer who's using pytest with otel,  their  second import of langsmith.client (during pytest unit test run time) weren't able to override initial one (during langsmith_plugin pytest plugin import, happened at very first of pytest set up).  This is causing subtle issue like if pytest plugin run first (`has_otel=False`), then later even if env var got reset (`has_otel=True`) the python still doesn't recognize the change.
I also found that the env var cache a bit problematic in such case, but if we fix the import, that might be less concerning, so i just reduced max size a …

fix: move otel check to client init time to avoid timing issue

---

python/langsmith/_internal/otel/_otel_exporter.py
python/tests/integration_tests/test_client.py

Prevents gen_ai.operation.name from being unintentionally reset to "chain" during spec conversion.
The issue stems from a missing run_type in update_run.

fix(python): Avoid resetting operation.name to "chain" during update_run

---

python/langsmith/_internal/otel/_otel_exporter.py
python/langsmith/client.py
python/tests/integration_tests/test_client.py
python/tests/unit_tests/test_otel_exporter.py

Problem: 
Memory leak when otel exporter process traces that never ended. Specifically,  the OTEL exporter stores spans for correlation between post (create) and patch (update) operations, but spans are only cleaned up when patch operations contain end_time. Those span that doesn't have end_time stays there forever now  
Solution:
Adds a proactive span cleanup:
- TTL-based cleanup: Remove spans older than 2 hours
- Count-based limits: Cap maximum spans at 100,000 
- Proactive processing: Clean up before each batch to prevent accumulation
Want to see if this remediates problem for customer OOM, if it works we can follow up on further fine tune the clean up logic such as make max_count and ttl configurable  
Test: 
- test hybrid and otel-only mode still sends trace to right party(s) 
- …

fix: memory leak risk from otel exporter persistance

---

python/langsmith/_internal/_background_thread.py
python/langsmith/_internal/_operations.py
python/langsmith/client.py
python/tests/unit_tests/test_client.py
python/tests/unit_tests/test_multiple_endpoints.py

If you are tracing many runs on multiple threads, due to threading batches can exceed stated size limits
This is more complex to fix when run compression is enabled due to incremental compression, but this PR allows for restricting this when run compression is disabled

feat(py): Allow overriding max batch size parameter on client, fix for disabled run compression

---

python/langsmith/run_helpers.py

When using from __future__ import annotations, attachment parameters were not correctly detected because annotations were stored as strings.
This updates the attachment-recognition logic to resolve stringified annotations with `get_type_hints`.

fix(python): Correctly recognize attachment with stringified annotations

---

python/langsmith/_internal/otel/_otel_exporter.py

fix long standing memory issue 
- Storage of Already-Ended Spans: _create_span_for_run() would create and immediately end spans (for fast operations with end_time), but export_batch() would still store these ended spans in _span_info, where they would never be cleaned up. Found this when i manually log every added / completed span and found that pretty much most of the fast operations are not cleaned up. 
Fix:  prevent storage of ended spans by checking if it's still active

fix: storage of already ended spans causes memory growth

---

js/src/client.ts
js/src/tests/client.test.ts
js/src/utils/error.ts

`await response.text()` will throw an error if the body is empty. If this happens, it overrides the existing error and does not set a status code, causing it to be retried inappropriately.

fix(js): Fix retries for empty bodies

---

python/langsmith/__init__.py
python/langsmith/_internal/otel/_otel_exporter.py
python/pyproject.toml

Fix issue https://github.com/langchain-ai/langsmith-sdk/issues/2005
Issue: We introduced the memory leak fix in previous PR to Only store spans that are still active (not already ended), but this had caused side-effect issue when child span cannot find the parent span context. 
Fix: Partially revert the previous change and keeps (a bit dangerously from memory perspective) all spans from _create_span_for_run even though span already ended.  Rely on span TTL (3600 sec by default, configurable).
Note:  This is like a bandaid unfortunatley. The fundamental fix instead should be a large re-architect of combine_serialized_queue_operations to make sure parent's don't merge _Creation+Update_ until all children has merged and merged children operation should come first to make sure. That's not …

fix: Store ended span to reserve parent span context

---

python/langsmith/__init__.py
python/pyproject.toml
python/uv.lock

since https://github.com/langchain-ai/langsmith-sdk/pull/2021 is out

version bump after new method 0.4.29

---

python/langsmith/__init__.py
python/langsmith/_internal/_background_thread.py
python/langsmith/client.py
python/langsmith/run_helpers.py
python/langsmith/run_trees.py
python/langsmith/utils.py
python/pyproject.toml
python/uv.lock

Once RunTree is posted, we don't need to keep the `child_runs` around anymore
Resolves https://github.com/langchain-ai/langsmith-sdk/issues/2009

Clear children after runtree posts

---

js/src/experimental/vercel/index.ts
js/src/tests/vercel/wrapper/openai.int.test.ts

fix(js): Copy object prototype when copying tools in AI SDK wrapper
