langchain-ai/langsmith-sdk

- js/src/client.ts
- python/langsmith/__init__.py
- python/langsmith/client.py
- python/langsmith/utils.py
- python/tests/integration_tests/test_client.py
- python/tests/unit_tests/test_client.py
Rm `LangChain+` from error messages and docstrings
> Update docstrings and error messages

- js/src/client.ts
- js/src/tests/client.int.test.ts
- python/langsmith/client.py
> Fix bug in dataset upload

- js/src/cli/docker-compose.dev.yaml
- js/src/cli/main.ts
- python/langsmith/cli/docker-compose.dev.yaml
- python/langsmith/cli/main.py
Plus fix stdout streaming from child process in JS CLI
> Separate Dev and Prod Volumes

- python/langsmith/client.py
- python/langsmith/schemas.py
(already was done client side in the TS client)
> Add Feedback ID

- js/src/cli/main.ts
- python/langsmith/cli/main.py
- python/langsmith/run_helpers.py
- python/tests/integration_tests/test_runs.py
Add support for tags/metadata to be inserted dynamically. Move langsmith thigns to a `langsmith_extra` key to avoid namespace collisions
> Add dynamic tag support

- python/langsmith/schemas.py
I thought we had decided to remove all validation from SDK and rely on server instead?
> Add two more run types for Runnable

- python/langsmith/cli/docker-compose.yaml
Fixes LS-499
Untested until I'm able to build docker images again
> Add redis+rq task queue to CLI docker compose file

- python/langsmith/__init__.py
- python/langsmith/run_helpers.py
- python/langsmith/run_trees.py
> Merge tags

- python/langsmith/evaluation/evaluator.py
> Fallback asyncio

- python/langsmith/evaluation/evaluator.py
- python/langsmith/run_trees.py
- python/langsmith/schemas.py
- python/pyproject.toml
Code is both v1 and v2 compatible
> Code to be both pydantic v1 and v2 compatible

- python/langsmith/run_trees.py
Run tree errors aren't really being visibly logged as they occur in the background thread. This PR makes it so that they are visible so long as you call `.wait()`
> improve errors

- js/src/client.ts
- js/src/evaluation/evaluator.ts
- js/src/evaluation/string_evaluator.ts
- js/src/tests/client.int.test.ts
- js/src/tests/run_trees.int.test.ts
- python/langsmith/client.py
- python/langsmith/evaluation/evaluator.py
- python/tests/integration_tests/test_client.py
Fixes up the updateFeedback api
> Update Feedback UX

- js/src/cli/main.ts
- js/src/client.ts
- js/src/tests/client.int.test.ts
- js/src/utils/env.ts
- python/langsmith/cli/main.py
- python/langsmith/client.py
- python/langsmith/env.py
- python/poetry.lock
- python/pyproject.toml
- python/tests/integration_tests/test_client.py
> Add support for hiding inputs/outputs via env var

- python/langsmith/client.py
- python/langsmith/run_helpers.py
> Make Metadata/tags Inheritable

- js/package.json
- js/src/client.ts
- python/langsmith/client.py
- python/pyproject.toml
> Read OAI Ft Dataset Method

- python/langsmith/client.py
- python/pyproject.toml
- python/tests/unit_tests/test_client.py
For pydantic objects in the json, try to use their method to serialize
> Better pydantic serialization

- python/langsmith/client.py
- python/langsmith/schemas.py
- python/tests/unit_tests/test_client.py
> Read Share Dataset

- js/package.json
- js/src/schemas.ts
- python/langsmith/schemas.py
- python/pyproject.toml
Update the types of the objects
> Update TS types

- python/langsmith/run_helpers.py
- python/pyproject.toml
- python/tests/unit_tests/test_client.py
Previously, mypy would complain when using strict typing
> Update @traceable Generic Typing

- js/src/client.ts
POST /runs creates new runs.
To query we need to use POST /runs/query.
> Fix the calls to listRun

- python/langsmith/client.py
- python/langsmith/utils.py
- python/tests/unit_tests/test_client.py
- if on, starts a background thread that batches inserts/updates
- only applies to insert/updates w/ trace_id and dotted_order
- after release, bump sdk version here https://github.com/langchain-ai/langchain/pull/16305
> Add auto_batch_tracing modality for Client

- .github/actions/js-integration-tests/action.yml
- .github/actions/python-integration-tests/action.yml
- .github/workflows/integration_tests.yml
- js/src/tests/client.int.test.ts
- python/Makefile
- python/langsmith/client.py
> Fixup int tests

- js/package.json
- js/src/client.ts
- js/src/schemas.ts
- js/src/tests/batch_client.int.test.ts
- js/src/tests/batch_client.test.ts
- js/src/tests/client.int.test.ts
CC @nfcampos @hinthornw
Unit tests done.
Supersedes #383
> Adds auto batch tracer support for JS

- js/package.json
- js/src/index.ts
- python/pyproject.toml
> Bump version

- js/README.md
> Fix typos in JS readme

- js/package.json
- js/src/client.ts
- js/src/index.ts
- js/src/tests/batch_client.int.test.ts
- js/src/tests/lcls_handoff.int.test.ts
- js/src/tests/run_trees.int.test.ts
- js/src/tests/utils.ts
A fix in run tree client passing if tracing isn't turned on
+ a better handoff btween langchainjs and traceable/run trees
> [JS Release] 0.1.5

- js/src/client.ts
- js/src/tests/batch_client.test.ts
This way, if an error occurs in a background autobatch processing run, it will be logged instead of bubbling up an error that is uncatchable to the user.
@hinthornw @dqbd @barberscott
> Improve JS async error handling for batch runs

- js/src/client.ts
- js/src/tests/batch_client.test.ts
> Respect batch byte size limits in JS client

- js/src/client.ts
> Add traceFilter to TS list runs endpoint

- python/langsmith/client.py
- python/pyproject.toml
> Add dataset version args to runner

- python/langsmith/client.py
- python/pyproject.toml
Less useful in python outside of e.g., streamlit, but still good to include
> Create presigned feedback

- python/langsmith/__init__.py
- python/langsmith/client.py
- python/langsmith/evaluation/__init__.py
- python/langsmith/evaluation/_runner.py
- python/pyproject.toml
- Take `evaluate` out of beta
- Fix up some docstrings
- Improve some typehints for cold start values
> Imports and dostring formatting

- python/langsmith/_internal/_aiter.py
- python/langsmith/evaluation/__init__.py
- python/langsmith/evaluation/_arunner.py
- python/langsmith/evaluation/_runner.py
- python/langsmith/wrappers/_openai.py
- python/pyproject.toml
- python/tests/integration_tests/test_runs.py
> Implement Aevaluate

- js/src/tests/traceable.int.test.ts
- js/src/traceable.ts
> Adds getCurrentRunTree method to TS

- .github/actions/python-integration-tests/action.yml
- .github/workflows/python_test.yml
- python/langsmith/_internal/_aiter.py
- python/langsmith/run_helpers.py
- python/tests/unit_tests/test_run_helpers.py
Finally start using `create_task` and copying the context to scope any changes to the tree.
Fixes #607
> Fix AsyncGenerator Tracing

- js/package.json
- js/src/index.ts
- js/src/tests/wrapped_openai.int.test.ts
- js/src/traceable.ts
> Respect env var for tracing in TS

- python/pyproject.toml
- Explicit arg for listing examples by metadata
> [Python] 0.1.53

- js/src/run_trees.ts
- js/src/tests/run_trees.int.test.ts
- js/src/tests/run_trees.test.ts
> fix(js): store execution order number in dotted order

- js/jest.config.cjs
- js/package.json
- js/src/index.ts
- js/src/run_trees.ts
- js/src/tests/run_trees.int.test.ts
- js/src/tests/run_trees.test.ts
- js/src/tests/traceable.test.ts
- js/src/tests/utils/mock_client.ts
- js/src/tests/utils/tree.ts
- js/src/traceable.ts
> fix(js): allow passing run tree manually

- python/langsmith/client.py
`feedack_block` -> `feedback_block`
> Fix typo in feedback client

- js/package.json
- js/src/index.ts
- js/src/run_trees.ts
- js/src/tests/run_trees.test.ts
- Adds support for distributed tracing via `.fromHeaders` / `.toHeaders` / `.fromDottedOrder` methods
> feat(js): add distributed tracing

- python/langsmith/run_helpers.py
- before it was creating the run with a separate root run
> Fix tracing for as_runnable

- python/langsmith/wrappers/_openai.py
- python/tests/integration_tests/wrappers/test_openai.py
> [Python] Custom Run Name support in OpenAI Client

- python/langsmith/run_helpers.py
- python/pyproject.toml
- python/tests/unit_tests/test_run_helpers.py
Previously there was an error in signature.replace
> [Python] Improve kwarg support in @traceable

- python/langsmith/run_helpers.py
- python/pyproject.toml
- python/tests/unit_tests/test_run_helpers.py
Closes https://github.com/langchain-ai/langsmith-sdk/issues/763
> Honor client when dist tracing

- python/langsmith/__init__.py
- python/pyproject.toml
Add tracing_context, get_current_tracing_context, and get_current_run_tree to top-level imports
> [Python] Add to top-level imports

- python/langsmith/client.py
In the request_with_retries method
> [Python] Handle 429

- python/langsmith/client.py
- python/langsmith/run_helpers.py
- python/tests/integration_tests/wrappers/test_openai.py
- python/tests/unit_tests/test_client.py
- python/tests/unit_tests/test_run_helpers.py
Additional retries beyond the urllib3 ones we've configured
> [Python] Add retries to remaining endpoints

- .github/workflows/python_test.yml
- python/langsmith/run_trees.py
- python/pyproject.toml
- python/tests/unit_tests/test_run_helpers.py
When loading from runnable config
> [Python] Pass through IO

- .github/workflows/python_test.yml
- python/langsmith/client.py
- python/langsmith/evaluation/_runner.py
- python/tests/unit_tests/test_utils.py
> Add python 3_9 and 3_10 to test matrix

- python/langsmith/client.py
This is already done in batch_ingest anyway
> [Python] Fetch env data in background

- python/langsmith/client.py
- python/langsmith/run_trees.py
- python/pyproject.toml
> Permit null run id in feedback create

- python/langsmith/run_helpers.py
- python/pyproject.toml
- python/tests/unit_tests/test_run_helpers.py
exposed via the same `trace` CM.
Would resolve https://github.com/langchain-ai/langsmith-sdk/issues/882
> Async trace context manager

- js/package.json
- js/src/index.ts
> js[patch]: Release 0.1.40

- js/src/run_trees.ts
- js/src/tests/lcls_handoff.int.test.ts
> Fix dotted_order and trace_id for deeply nested JS interop traces

- python/langsmith/run_helpers.py
- python/poetry.lock
- python/pyproject.toml
- python/tests/unit_tests/test_run_helpers.py
Sync only (since python async generators dont' support it anyhow)
> [Py] Suport yield & return from wrapped generators

- python/langsmith/evaluation/_runner.py
> Fix multi-pairwise evaluation

- python/langsmith/_internal/_aiter.py
- python/langsmith/evaluation/_arunner.py
- python/langsmith/evaluation/_runner.py
- python/pyproject.toml
- python/tests/unit_tests/evaluation/test_runner.py
Reported by Adham
useful for generating custom dashboards / iterating eagerly
> Support eager iteration of results in evaluate

- js/package.json
- js/src/client.ts
- js/src/index.ts
- python/langsmith/client.py
- python/pyproject.toml
When sampling, don't randomly sample within a trace; sample whole traces only.
> Filter Root (not children)

- python/langsmith/client.py
- python/langsmith/evaluation/_arunner.py
- python/langsmith/evaluation/_runner.py
And then will be even better once we add batch endpoint
> [Python] Evals: submit feedback in thread

- js/src/client.ts
- js/src/tests/batch_client.test.ts
- js/src/tests/traceable.test.ts
- js/src/utils/serde.ts
~~This does add a few stringify calls - we could do this more efficiently if needed but I am not sure it's worth prematurely optimizing~~
Fixes #962
> fix(js): Adds fix for circular references in inputs and outputs

- python/langsmith/evaluation/evaluator.py
- python/langsmith/run_helpers.py
- python/langsmith/run_trees.py
- python/langsmith/utils.py
- python/pyproject.toml
- python/tests/evaluation/test_evaluation.py
- python/tests/unit_tests/evaluation/test_evaluator.py
- python/tests/unit_tests/test_run_trees.py
- python/tests/unit_tests/test_utils.py
> [Python] Use _name 

- python/langsmith/client.py
Was reading through sdk and came across a few copy-pasta descriptions
> Fix two descriptions in python sdk

- python/langsmith/run_trees.py
- python/pyproject.toml
- python/tests/evaluation/test_evaluation.py
For events.
Needed before removing core's Run subclass
> [Py] Add default_factory in run tree

- python/langsmith/_expect.py
- python/langsmith/_internal/_embedding_distance.py
- python/langsmith/_testing.py
- python/langsmith/beta/_evals.py
- python/langsmith/evaluation/_arunner.py
- python/langsmith/evaluation/_runner.py
- python/langsmith/run_trees.py
- python/pyproject.toml
Also use cached client for defaults in testing to avoid creating new threads
> [Py] Default to unnamed

- python/langsmith/client.py
> Adding method for removing a run from an annotation queue

- python/langsmith/client.py
So if you are using it on a run tree
> Fix run url new proj

- python/langsmith/client.py
> List limit

- python/langsmith/client.py
- python/langsmith/run_trees.py
- python/langsmith/schemas.py
- python/pyproject.toml
- python/tests/unit_tests/test_client.py
> [Py]Better mock handling in serialization

- python/langsmith/client.py
- python/langsmith/run_helpers.py
- python/langsmith/run_trees.py
- python/langsmith/schemas.py
- python/pyproject.toml
- python/tests/unit_tests/test_run_helpers.py
Add support for logging certain arguments to traceable functions as annotations.
Also fixes a bug where annotations were being deleted prior to being added to the tracing queue.
> Annotation Support

- js/package.json
- js/src/index.ts
- js/src/vercel.ts
- **feat(vercel): add debug flag**
- **Bump to 0.2.4-dev.0**
- **Prevent unnecessary nesting**
> feat(vercel): add debug flag

- js/package.json
- js/src/index.ts
- js/src/tests/vercel.int.test.ts
- js/src/tests/vercel.test.ts
- js/src/vercel.ts
https://github.com/langchain-ai/langsmith-docs/pull/506
> fix(vercel): add more debug logs, fix tracing detection for vercel, bump to 0.2.4

- python/langsmith/_internal/_serde.py
- python/langsmith/client.py
- python/langsmith/run_helpers.py
- python/tests/unit_tests/test_client.py
Right now if you make a client pointing to another server but try to clone from the public saas server it fails.
> Fix clone dataset from other server

- python/langsmith/evaluation/_arunner.py
- python/langsmith/evaluation/_runner.py
- python/tests/evaluation/test_evaluation.py
> [Python] to_pandas() method for ExperimentResults

- python/langsmith/evaluation/_runner.py
Seems unnecessary that after i create a dataset i cant just pass in the dataset object to evaluate
> python[patch]: evaluate accept Dataset

- js/src/client.ts
seeing some timeouts at around 1s
> chore: increase server info request timeout

- rust/crates/langsmith-tracing-client/tests/tracing_client_test.rs
Needed to stop Rust linting from failing in CI.
> Fix formatting in Rust tracing client.

- python/langsmith/_internal/_background_thread.py
- python/langsmith/_internal/_compressed_runs.py
- python/langsmith/_internal/_operations.py
- python/langsmith/client.py
Report full and compressed content length to API for monitoring `zstd` compression ratio for real-world tracing
> feat: Report pre and post compressed content length to API

- python/langsmith/client.py
> python[patch]: handle deployments without attachments support

- python/langsmith/wrappers/_openai.py
- python/tests/integration_tests/wrappers/test_openai.py
Instrument tracing for OpenAI Structured Outputs
1. Created openai parser wrapper for structured outputs beta method `client.beta.chat.completions.parse`
1. Added support for both sync and async tracing
1. Maintains backwards compatibility for clients that don't have beta parse methods
Added unit tests for parsing methods, and token counts. Tested locally to confirm parsing gets traced
> [!NOTE]  
> Parsing does not support streaming, so the `reduce_fn` is always set to None
> feat: Instrument wrapper for OpenAI structured outputs

- python/tests/integration_tests/test_prompts.py
Updated behavior in langchain-openai 0.3
> python[patch]: update OpenAI prompt test

- .github/actions/js-integration-tests/action.yml
- .github/actions/python-integration-tests/action.yml
- README.md
- js/README.md
- python/README.md
> docs: Update preferred env vars in READMEs and CI

- python/langsmith/pytest_plugin.py
- python/langsmith/testing/_internal.py
- python/pyproject.toml
- properly lock access updating shared resource
- correctly pull modified_at when updating example
> python[patch]: fix pytest integration example syncing

- python/langsmith/client.py
stop sending timezone-less created_at time. backend handles setting this
> fix(py): fix dataset created_at

- js/package.json
- js/yarn.lock
> fix(js): Bump Vitest devdep

- python/langsmith/run_helpers.py
- python/pyproject.toml
- python/tests/unit_tests/test_run_helpers.py
allow processing of chunks for tracing when using `traceable` with a streaming function
> feat(py): suppoer traceable(process_chunk=)

- .github/workflows/integration_tests.yml
- .github/workflows/python_test.yml
https://github.com/actions/runner-images/issues/11101
> chore: upgrade ubuntu 20.04->22.04 for deprecation

- python/langsmith/client.py
- python/tests/integration_tests/test_client.py
fixes: https://github.com/langchain-ai/langsmith-sdk/issues/1582
> fix delete examples [LS-3226]

- js/src/traceable.ts
- js/yarn.lock
> chore(js): update dev deps

- python/langsmith/wrappers/_openai_agents.py
- python/pyproject.toml
Populate Threads view from `group_id` param
> Add group id thread tracing for OpenAI Agents SDK

- js/package.json
- js/src/client.ts
- js/src/evaluation/_runner.ts
- js/src/evaluation/evaluate_comparative.ts
- js/src/index.ts
- js/src/singletons/fetch.ts
- js/src/tests/batch_client.int.test.ts
- js/src/tests/batch_client.test.ts
- js/src/utils/async_caller.ts
Enabled by passing `debug: true` to a client or by setting `LANGSMITH_DEBUG="true"`
> feat(js): Adds JS debug mode that logs output request URLs and responses

- python/poetry.lock
- python/pyproject.toml
Will open similar PRs across our repos, but given that this is one of the lowest level deps, wanted to tackle this one first.
> packaging: remove Python upper bound

- js/package.json
- js/src/index.ts
- js/src/utils/jestlike/vendor/evaluatedBy.ts
> fix(js): Make feedback for evaluator traces using evaluatedBy for jestlike runs apply to root runs

- js/package.json
- js/yarn.lock
> fix(js): Upgrade vite devdep

- js/src/run_trees.ts
Seems like an oversight?
CC @lc-arjun
> fix(js): Pass events through on run create

- js/src/run_trees.ts
> fix(js): Avoid overwriting runtime if already set

- js/src/experimental/otel/constants.ts
- js/src/experimental/otel/exporter.ts
- js/src/tests/otel/vercel/ai_sdk_evaluate.int.test.ts
- js/src/traceable.ts
This is necessary to pass through when tracing via OTEL and running experiments.
> feat(js): Add reference_example_id attribute to OTEL runs

- js/src/client.ts
Matches Python:
https://github.com/langchain-ai/langsmith-sdk/blob/main/python/langsmith/client.py#L4462
> fix(js): Add endpoint shim to example upload

- js/src/client.ts
> fix(js): Make readDataset throw if empty string is passed

- python/langsmith/wrappers/_agent_utils.py
- python/pyproject.toml
- python/tests/integration_tests/cassettes/test_openai_agents_test_openai_agents_tracing_processor.yaml
- python/tests/integration_tests/wrappers/test_openai_agents.py
- python/uv.lock
> fix(python): Remove upper bound for OpenAI agents

- python/langsmith/run_trees.py
set replicas once per run tree, instead of once per post/patch call
> chore(python): Cleanup replica setting

- js/src/client.ts
- js/src/schemas.ts
- python/langsmith/_internal/_operations.py
- python/langsmith/client.py
- python/tests/integration_tests/test_async_client.py
- python/tests/integration_tests/test_client.py
- python/tests/unit_tests/test_client.py
- python/tests/unit_tests/test_run_helpers.py
Pop all OOB keys for better ingestion performance
> perf(python, js): Pop all allowed oob keys

- python/langsmith/wrappers/_openai_agents.py
Check for current trace before starting a new one in openai agents wrapper
> feat(pythong): allow nested openai agent tracing

- python/langsmith/client.py
> feat(py): Fix list_projects typing, add dataset_version param

- js/src/tests/jestlike/jest_existing_dataset.int.test.ts
- js/src/utils/jestlike/index.ts
- js/src/utils/jestlike/types.ts
> feat(js): Allow manually specifying ids for examples in Jestlike runners

- .github/workflows/js_test.yml
- js/package.json
- js/src/experimental/vercel/index.ts
- js/src/experimental/vercel/middleware.ts
- js/src/tests/vercel/wrapper/anthropic.int.test.ts
- js/src/tests/vercel/wrapper/methods.vitesttest.ts
- js/src/traceable.ts
- js/vitest.config.ts
- js/yarn.lock
> fix(js): Fix output processing for AI SDK streamText

- python/langsmith/__init__.py
- python/langsmith/wrappers/_openai_agents.py
- python/pyproject.toml
- python/tests/integration_tests/wrappers/test_openai_agents.py
- python/uv.lock
> fix(py): Inherit project name from parent for OpenAI agent wrapper

- python/langsmith/client.py
simply should not have used doctest
> fix: docstring of get_expeirment_results 
